version: "3"

services:
  app_service:
    container_name: app_service
    build: .
  postgresql:
    image: postgres:15.0
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PWD}
    volumes:
      - psql:/var/lib/psql
volumes:
  psql: